services:
  - type: web
    name: kanteeno-ui-viewer-v2
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
